[07-Oct-2022 14:43:53 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:46:40 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function query() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#1 [internal function]: App\Controllers\Posts->indexAction()
#2 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#4 C:\xampp\htdocs\simpl\public\index.php(35): Core\Router->dispatch('posts')
#5 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 14:48:20 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:19 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:20 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:20 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function query() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#1 [internal function]: App\Controllers\Posts->indexAction()
#2 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#4 C:\xampp\htdocs\simpl\public\index.php(35): Core\Router->dispatch('posts')
#5 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 14:54:22 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:26 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function query() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#1 [internal function]: App\Controllers\Posts->indexAction()
#2 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#4 C:\xampp\htdocs\simpl\public\index.php(35): Core\Router->dispatch('posts')
#5 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 14:54:27 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:28 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:36 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function query() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#1 [internal function]: App\Controllers\Posts->indexAction()
#2 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#4 C:\xampp\htdocs\simpl\public\index.php(35): Core\Router->dispatch('posts')
#5 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 14:54:36 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:37 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:38 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 14:54:38 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function query() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#1 [internal function]: App\Controllers\Posts->indexAction()
#2 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#4 C:\xampp\htdocs\simpl\public\index.php(35): Core\Router->dispatch('posts')
#5 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 14:54:39 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 15:07:15 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 15:07:18 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 15:12:46 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 15:12:49 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function prepare() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\public\index.php(37): App\Models\Post::getPost(3)
#1 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 40
[07-Oct-2022 15:14:32 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function query() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#1 [internal function]: App\Controllers\Posts->indexAction()
#2 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#4 C:\xampp\htdocs\simpl\public\index.php(35): Core\Router->dispatch('posts')
#5 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 15:16:48 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to a member function query() on null' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#1 [internal function]: App\Controllers\Posts->indexAction()
#2 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#4 C:\xampp\htdocs\simpl\public\index.php(35): Core\Router->dispatch('posts')
#5 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 15:34:46 Europe/Berlin] Uncaught exception: 'Exception' with message: 'Not Found' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\Router.php(46): Core\ErrorHandler::throwAndLogErr('No route mached', 'Not Found', 404)
#1 C:\xampp\htdocs\simpl\public\index.php(35): Core\Router->dispatch('postsx')
#2 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\ErrorHandler.php' on line 13
[07-Oct-2022 15:38:18 Europe/Berlin] Uncaught exception: 'Exception' with message: 'Not Found' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\Router.php(46): Core\ErrorHandler::throwAndLogErr('No route mached', 'Not Found', 404)
#1 C:\xampp\htdocs\simpl\public\index.php(33): Core\Router->dispatch('posts/id:3')
#2 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\ErrorHandler.php' on line 13
[07-Oct-2022 15:39:27 Europe/Berlin] Uncaught exception: 'Exception' with message: 'Not Found' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\Router.php(46): Core\ErrorHandler::throwAndLogErr('No route mached', 'Not Found', 404)
#1 C:\xampp\htdocs\simpl\public\index.php(33): Core\Router->dispatch('posts/id:3')
#2 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\ErrorHandler.php' on line 13
[07-Oct-2022 15:39:28 Europe/Berlin] Uncaught exception: 'Exception' with message: 'Not Found' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\Router.php(46): Core\ErrorHandler::throwAndLogErr('No route mached', 'Not Found', 404)
#1 C:\xampp\htdocs\simpl\public\index.php(33): Core\Router->dispatch('posts/id:3')
#2 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\ErrorHandler.php' on line 13
[07-Oct-2022 15:39:31 Europe/Berlin] Uncaught exception: 'Exception' with message: 'Not Found' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\Router.php(46): Core\ErrorHandler::throwAndLogErr('No route mached', 'Not Found', 404)
#1 C:\xampp\htdocs\simpl\public\index.php(33): Core\Router->dispatch('posts/id:3')
#2 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\ErrorHandler.php' on line 13
[07-Oct-2022 15:39:31 Europe/Berlin] Uncaught exception: 'Exception' with message: 'Not Found' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\Router.php(46): Core\ErrorHandler::throwAndLogErr('No route mached', 'Not Found', 404)
#1 C:\xampp\htdocs\simpl\public\index.php(33): Core\Router->dispatch('posts/id:3')
#2 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\ErrorHandler.php' on line 13
[07-Oct-2022 15:54:29 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to undefined method App\Models\Post::getDummyPostsAll()' 
Stack trace: '#0 [internal function]: App\Controllers\Posts->indexAction()
#1 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#4 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Controllers\Posts.php' on line 24
[07-Oct-2022 15:54:32 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to undefined method App\Models\Post::getDummyPostsAll()' 
Stack trace: '#0 [internal function]: App\Controllers\Posts->indexAction()
#1 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#4 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Controllers\Posts.php' on line 24
[07-Oct-2022 15:54:35 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to undefined method App\Models\Post::getDummyPostsAll()' 
Stack trace: '#0 [internal function]: App\Controllers\Posts->indexAction()
#1 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('')
#4 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Controllers\Posts.php' on line 24
[07-Oct-2022 15:54:56 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to undefined method App\Models\Post::getDummyPostsAll()' 
Stack trace: '#0 [internal function]: App\Controllers\Posts->indexAction()
#1 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('')
#4 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Controllers\Posts.php' on line 24
[07-Oct-2022 15:54:57 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to undefined method App\Models\Post::getDummyPostsAll()' 
Stack trace: '#0 [internal function]: App\Controllers\Posts->indexAction()
#1 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('')
#4 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Controllers\Posts.php' on line 24
[07-Oct-2022 15:54:57 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to undefined method App\Models\Post::getDummyPostsAll()' 
Stack trace: '#0 [internal function]: App\Controllers\Posts->indexAction()
#1 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('')
#4 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Controllers\Posts.php' on line 24
[07-Oct-2022 15:54:57 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to undefined method App\Models\Post::getDummyPostsAll()' 
Stack trace: '#0 [internal function]: App\Controllers\Posts->indexAction()
#1 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('')
#4 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Controllers\Posts.php' on line 24
[07-Oct-2022 15:55:01 Europe/Berlin] Uncaught exception: 'Error' with message: 'Call to undefined method App\Models\Post::getDummyPostsAll()' 
Stack trace: '#0 [internal function]: App\Controllers\Posts->indexAction()
#1 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#3 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#4 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Controllers\Posts.php' on line 24
[07-Oct-2022 16:12:45 Europe/Berlin] Uncaught exception: 'Error' with message: 'Class 'App\Models\FakeDB' not found' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#1 [internal function]: App\Controllers\Posts->indexAction()
#2 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#4 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#5 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 14
[07-Oct-2022 16:13:24 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Non-static method Core\FakeDB::query() should not be called statically' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\Error::errorHandler(8192, 'Non-static meth...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#2 [internal function]: App\Controllers\Posts->indexAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 15
[07-Oct-2022 16:21:01 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'private' (T_PRIVATE), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:21:59 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'private' (T_PRIVATE), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:22:00 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'private' (T_PRIVATE), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:22:00 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'private' (T_PRIVATE), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:23:35 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:23:36 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:23:36 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:24:16 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:24:16 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:24:16 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:24:16 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:25:54 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:25:55 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:25:55 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:30:03 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'file_get_contents(fakedb.json): failed to open stream: No such file or directory' 
Stack trace: '#0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 13, Array)
#1 C:\xampp\htdocs\simpl\Core\FakeDB.php(13): file_get_contents('fakedb.json')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 13
[07-Oct-2022 16:32:08 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'file_get_contents(./akedb.json): failed to open stream: No such file or directory' 
Stack trace: '#0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\simpl\Core\FakeDB.php(14): file_get_contents('./akedb.json', true)
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 14
[07-Oct-2022 16:32:08 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'file_get_contents(./akedb.json): failed to open stream: No such file or directory' 
Stack trace: '#0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\simpl\Core\FakeDB.php(14): file_get_contents('./akedb.json', true)
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 14
[07-Oct-2022 16:32:16 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'file_get_contents(./fakedb.json): failed to open stream: No such file or directory' 
Stack trace: '#0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\simpl\Core\FakeDB.php(14): file_get_contents('./fakedb.json', true)
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 14
[07-Oct-2022 16:32:17 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'file_get_contents(./fakedb.json): failed to open stream: No such file or directory' 
Stack trace: '#0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\simpl\Core\FakeDB.php(14): file_get_contents('./fakedb.json', true)
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 14
[07-Oct-2022 16:38:15 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:38:36 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:38:37 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:38:47 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:38:48 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:38:48 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:38:48 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:39:16 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:39:17 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 9
[07-Oct-2022 16:40:10 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '{'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 20
[07-Oct-2022 16:40:11 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '{'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 20
[07-Oct-2022 16:40:11 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '{'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 20
[07-Oct-2022 16:40:30 Europe/Berlin] Uncaught exception: 'Error' with message: 'Using $this when not in object context' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#2 [internal function]: App\Controllers\Posts->indexAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 102
[07-Oct-2022 16:41:10 Europe/Berlin] Uncaught exception: 'Error' with message: 'Using $this when not in object context' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#2 [internal function]: App\Controllers\Posts->indexAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 102
[07-Oct-2022 16:41:43 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Undefined variable: dbJsonStr' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\FakeDB.php(102): Core\Error::errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 102, Array)
#1 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 102
[07-Oct-2022 16:42:12 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Undefined variable: dbJsonStr' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\FakeDB.php(96): Core\Error::errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 96
[07-Oct-2022 16:42:13 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Undefined variable: dbJsonStr' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\FakeDB.php(96): Core\Error::errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 96
[07-Oct-2022 16:42:13 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Undefined variable: dbJsonStr' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\FakeDB.php(96): Core\Error::errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 96
[07-Oct-2022 16:42:13 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Undefined variable: dbJsonStr' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\FakeDB.php(96): Core\Error::errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 96
[07-Oct-2022 16:45:35 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'file_get_contents(./fakedb.json): failed to open stream: No such file or directory' 
Stack trace: '#0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\simpl\Core\FakeDB.php(14): file_get_contents('./fakedb.json', true)
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 14
[07-Oct-2022 16:46:27 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'file_get_contents({
    &quot;Lecturers&quot;: [
      {
        &quot;id&quot;: &quot;1&quot;,
        &quot;name&quot;: &quot;Moshe&quot;,
        &quot;email&quot;: &quot;moshe@example.com&quot;,
        &quot;languages&quot;: [
          1,
          3
        ]
      },
      {
        &quot;id&quot;: &quot;20&quot;,
        &quot;name&quot;: &quot;Avi&quot;,
        &quot;email&quot;: &quot;avi@example.com&quot;,
        &quot;languages&quot;: [
          3
        ]
      },
      {
        &quot;id&quot;: &quot;300&quot;,
        &quot;name&quot;: &quot;Gila&quot;,
        &quot;email&quot;: &quot;gila@example.com&quot;,
        &quot;languages&quot;: [
          2,
          4,
          7
        ]
      },
      {
        &quot;id&quot;: &quot;400&quot;,
        &quot;name&quot;: &quot;Yonah&quot;,
        &quot;email&quot;: &quot;yonah@example.com&quot;,
        &quot;languages&quot;: [
          2,
          8,
          1
        ]
      }
    ],
    &quot;Languages&quot;: [
      {
        &quot;id&quot;: 1,
        &quot;name&quot;: &quot;Java&quot;
      },
      {
        &quot;id&quot;: 2,
        &quot;name&quot;: &quot;.NET&quot;
      },
      {
        &quot;id&quot;: 3,
        &quot;name&quot;: &quot;NodeJS&quot;
      },
      {
        &quot;id&quot;: 4,
        &quot;name&quot;: &quot;Advanced Vanilla JS&quot;
      },
      {
        &quot;id&quot;: 5,
        &quot;name&quot;: &quot;React&quot;
      },
      {
        &quot;id&quot;: 6,
        &quot;name&quot;: &quot;Angular&quot;
      },
      {
        &quot;id&quot;: 7,
        &quot;name&quot;: &quot;Kotlin&quot;
      },
      {
        &quot;id&quot;: 8,
        &quot;name&quot;: &quot;Dart&quot;
      },
      {
        &quot;id&quot;: 9,
        &quot;name&quot;: &quot;Flutter&quot;
      }
    ]
  }): failed to open stream: No such file or directory' 
Stack trace: '#0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 16, Array)
#1 C:\xampp\htdocs\simpl\Core\FakeDB.php(16): file_get_contents('{\r\n    "Lecture...')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 16
[07-Oct-2022 16:47:55 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:49:03 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:49:04 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:49:04 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:49:27 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 17
[07-Oct-2022 16:49:27 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 17
[07-Oct-2022 16:49:27 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 17
[07-Oct-2022 16:49:28 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 17
[07-Oct-2022 16:49:28 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 17
[07-Oct-2022 16:50:09 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 18
[07-Oct-2022 16:50:09 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 18
[07-Oct-2022 16:50:50 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:50:51 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:50:51 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:50:51 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:50:58 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:50:58 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:50:58 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '}', expecting ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Core\\FakeDB')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): spl_autoload_call('Core\\FakeDB')
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 15
[07-Oct-2022 16:51:14 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'file_get_contents({
    &quot;Lecturers&quot;: [
      {
        &quot;id&quot;: &quot;1&quot;,
        &quot;name&quot;: &quot;Moshe&quot;,
        &quot;email&quot;: &quot;moshe@example.com&quot;,
        &quot;languages&quot;: [
          1,
          3
        ]
      },
      {
        &quot;id&quot;: &quot;20&quot;,
        &quot;name&quot;: &quot;Avi&quot;,
        &quot;email&quot;: &quot;avi@example.com&quot;,
        &quot;languages&quot;: [
          3
        ]
      },
      {
        &quot;id&quot;: &quot;300&quot;,
        &quot;name&quot;: &quot;Gila&quot;,
        &quot;email&quot;: &quot;gila@example.com&quot;,
        &quot;languages&quot;: [
          2,
          4,
          7
        ]
      },
      {
        &quot;id&quot;: &quot;400&quot;,
        &quot;name&quot;: &quot;Yonah&quot;,
        &quot;email&quot;: &quot;yonah@example.com&quot;,
        &quot;languages&quot;: [
          2,
          8,
          1
        ]
      }
    ],
    &quot;Languages&quot;: [
      {
        &quot;id&quot;: 1,
        &quot;name&quot;: &quot;Java&quot;
      },
      {
        &quot;id&quot;: 2,
        &quot;name&quot;: &quot;.NET&quot;
      },
      {
        &quot;id&quot;: 3,
        &quot;name&quot;: &quot;NodeJS&quot;
      },
      {
        &quot;id&quot;: 4,
        &quot;name&quot;: &quot;Advanced Vanilla JS&quot;
      },
      {
        &quot;id&quot;: 5,
        &quot;name&quot;: &quot;React&quot;
      },
      {
        &quot;id&quot;: 6,
        &quot;name&quot;: &quot;Angular&quot;
      },
      {
        &quot;id&quot;: 7,
        &quot;name&quot;: &quot;Kotlin&quot;
      },
      {
        &quot;id&quot;: 8,
        &quot;name&quot;: &quot;Dart&quot;
      },
      {
        &quot;id&quot;: 9,
        &quot;name&quot;: &quot;Flutter&quot;
      }
    ]
  }): failed to open stream: No such file or directory' 
Stack trace: '#0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\simpl\Core\FakeDB.php(14): file_get_contents('{\r\n    "Lecture...')
#2 C:\xampp\htdocs\simpl\App\Models\Post.php(15): Core\FakeDB::query()
#3 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(24): App\Models\Post::getAll()
#4 [internal function]: App\Controllers\Posts->indexAction()
#5 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('index', Array)
#7 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts')
#8 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\FakeDB.php' on line 14
[07-Oct-2022 17:51:40 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 17:53:00 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(32): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 32, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 32
[07-Oct-2022 17:53:18 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(32): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 32, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 32
[07-Oct-2022 17:53:19 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(32): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 32, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 32
[07-Oct-2022 17:54:40 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(26): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 17:56:05 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\Post')
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): spl_autoload_call('App\\Models\\Post')
#3 [internal function]: App\Controllers\Posts->postbyidAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 17:56:19 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Invalid argument supplied for foreach()' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(26): Core\Error::errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 17:56:51 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Invalid argument supplied for foreach()' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(26): Core\Error::errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 17:56:52 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Invalid argument supplied for foreach()' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(26): Core\Error::errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 17:56:52 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Invalid argument supplied for foreach()' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(26): Core\Error::errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 17:57:15 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(26): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 26
[07-Oct-2022 18:01:32 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Trying to get property 'name' of non-object' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:02:39 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Undefined variable: name' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(28): Core\Error::errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 28
[07-Oct-2022 18:02:53 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected ';'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\Post')
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): spl_autoload_call('App\\Models\\Post')
#3 [internal function]: App\Controllers\Posts->postbyidAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 28
[07-Oct-2022 18:03:00 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(28): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 28
[07-Oct-2022 18:03:22 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Undefined offset: 0' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(28): Core\Error::errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 28
[07-Oct-2022 18:03:34 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Undefined offset: 1' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(28): Core\Error::errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 28
[07-Oct-2022 18:04:00 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:04:44 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:05:55 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:06:14 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:06:14 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:06:23 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:06:36 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:09:50 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(27): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 27
[07-Oct-2022 18:13:10 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Trying to get property 'name' of non-object' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(34): Core\Error::errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 34
[07-Oct-2022 18:13:23 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(34): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 34
[07-Oct-2022 18:14:07 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Trying to get property 'name' of non-object' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(34): Core\Error::errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 34
[07-Oct-2022 18:14:17 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Trying to get property 'name' of non-object' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(34): Core\Error::errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 34
[07-Oct-2022 18:14:17 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Trying to get property 'name' of non-object' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(34): Core\Error::errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 34
[07-Oct-2022 18:17:14 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'die' (T_EXIT), expecting function (T_FUNCTION) or const (T_CONST)' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\Post')
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): spl_autoload_call('App\\Models\\Post')
#3 [internal function]: App\Controllers\Posts->postbyidAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 46
[07-Oct-2022 18:17:27 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\Post')
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): spl_autoload_call('App\\Models\\Post')
#3 [internal function]: App\Controllers\Posts->postbyidAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 52
[07-Oct-2022 18:18:04 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\Post')
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): spl_autoload_call('App\\Models\\Post')
#3 [internal function]: App\Controllers\Posts->postbyidAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 56
[07-Oct-2022 18:18:05 Europe/Berlin] Uncaught exception: 'ParseError' with message: 'syntax error, unexpected 'public' (T_PUBLIC), expecting end of file' 
Stack trace: '#0 C:\xampp\htdocs\simpl\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\Post')
#2 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): spl_autoload_call('App\\Models\\Post')
#3 [internal function]: App\Controllers\Posts->postbyidAction()
#4 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#6 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#7 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 56
[07-Oct-2022 18:22:38 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(28): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 28
[07-Oct-2022 18:28:52 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Trying to get property 'name' of non-object' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(31): Core\Error::errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 31, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 31
[07-Oct-2022 18:29:06 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP)' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(31): Core\Error::errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 31, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 31
[07-Oct-2022 18:29:26 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Illegal string offset 'name'' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(31): Core\Error::errorHandler(2, 'Illegal string ...', 'C:\\xampp\\htdocs...', 31, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 31
[07-Oct-2022 18:29:37 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(31): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 31, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 31
[07-Oct-2022 18:31:41 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Trying to get property 'name' of non-object' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(32): Core\Error::errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 32, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 32
[07-Oct-2022 18:34:50 Europe/Berlin] Uncaught exception: 'ErrorException' with message: 'Array to string conversion' 
Stack trace: '#0 C:\xampp\htdocs\simpl\App\Models\Post.php(32): Core\Error::errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 32, Array)
#1 C:\xampp\htdocs\simpl\App\Controllers\Posts.php(37): App\Models\Post::getPost('3')
#2 [internal function]: App\Controllers\Posts->postbyidAction()
#3 C:\xampp\htdocs\simpl\Core\Controller.php(21): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\simpl\Core\Router.php(63): Core\Controller->__call('postbyid', Array)
#5 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/3')
#6 {main} 
Trown in : 'C:\xampp\htdocs\simpl\App\Models\Post.php' on line 32
[07-Oct-2022 18:38:30 Europe/Berlin] Uncaught exception: 'Exception' with message: 'Not Found' 
Stack trace: '#0 C:\xampp\htdocs\simpl\Core\Router.php(46): Core\ErrorHandler::throwAndLogErr('No route mached', 'Not Found', 404)
#1 C:\xampp\htdocs\simpl\public\index.php(31): Core\Router->dispatch('posts/')
#2 {main} 
Trown in : 'C:\xampp\htdocs\simpl\Core\ErrorHandler.php' on line 13
